### ISSUE TITLE
Install research package?

### ISSUE THREAD

**Issue by sandgatt** [osulp/archon#75]
It looks like we need to install the research package in order to manage the user profile and appointment function. I think we're currently missing it because we don't seem to have access some of the managers (like the Researcher Type Manager).

**Comment by mickeroo** [comment]
It looks like there was a change from version 2 to 3 that merged the features from the Research Package into the Archon core.  So instead of having a dedicated package, the features are enabled on a per-repository basis (Repository Manager -> SCARC -> Research Featues).

The appointments and researcher type settings are in the Collections section under Appointment Purposes Manager, Appointments Manager, and Researcher Types.  I think that should get you what you're looking for.

Also, if there are any UI changes for any of those forms (which I really haven't looked at yet) just put in an issue and I'll get them fixed.
